server:
  port: 8087
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: forum-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:consort-postgres}:${DB_PORT:5432}/${POSTGRES_DB:consort_group}}
    username: ${DB_USERNAME:${POSTGRES_USER:consort}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:consort}}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_FORUM_HOST:consort-redis-forum-service}
      port: ${REDIS_FORUM_PORT:6379}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

logging:
  level:
    root: INFO
    org.springframework: DEBUG

user:
  service:
    url: ${USER_SERVICE_URL:http://consort-user-service:8081}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://consort-eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${HOSTNAME}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
  health:
    redis:
      enabled: true
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha
    use-root-path: true
  model-converters:
    pageable-converter:
      enabled: true
