server:
  port: 8087

spring:
  application:
    name: forum-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: consort
    password: 2231251fsad1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6385

logging:
  level:
    root: INFO
    org.springframework: DEBUG

kafka:
  bootstrap-servers: localhost:9092
  consumer-group-id: forum-group
  session-timeout-ms: 10000
  max-partition-fetch-bytes: 1048576
  max-poll-records: 500
  max-poll-interval-ms: 300000
  course-group: course-group-opened-topic
  course-forum-group: course-forum-group-created-topic
  producer:
    enable: true