server:
  port: 8087

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: forum-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: consort-redis-forum-service
      port: 6379

logging:
  level:
    root: INFO
    org.springframework: DEBUG

kafka:
  bootstrap-servers: kafka:9092
  consumer-group-id: forum-group
  session-timeout-ms: 10000
  max-partition-fetch-bytes: 1048576
  max-poll-records: 500
  max-poll-interval-ms: 300000
  course-group: course-group-opened-topic
  course-forum-group: course-forum-group-created-topic
  producer:
    enable: true

user:
  service:
    url: http://consort-user-service:8081

course:
  service:
    url: http://consort-course-service:8084

security:
  token: ${SECURITY_TOKEN}
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8762/eureka/
  instance:
    prefer-ip-address: true
